/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type AssignContactsToListInputObject struct {
	// Comma-separated array of [Contacts](http://docs.textmagictesting.com/#tag/Contacts) IDs.
	Contacts string `json:"contacts"`
}
