/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type File struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	OriginalName string `json:"originalName"`
	MimeType string `json:"mimeType"`
	Size int32 `json:"size"`
	// File type.
	Type_ string `json:"type"`
	CreatedAt string `json:"createdAt"`
	PreviewUrl string `json:"previewUrl,omitempty"`
	Url string `json:"url,omitempty"`
	Metadata *FileMetadata `json:"metadata,omitempty"`
}
