/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MessageOutSenderSource struct {
	Id int32 `json:"id,omitempty"`
	Phone string `json:"phone,omitempty"`
	Type_ string `json:"type,omitempty"`
	CountryId string `json:"countryId,omitempty"`
	Label string `json:"label,omitempty"`
	Status string `json:"status,omitempty"`
	CarrierStatus string `json:"carrierStatus,omitempty"`
}
