/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type CreateEmailCampaignInputObject struct {
	// Email sender ID from your configured senders.
	EmailSenderId int32 `json:"emailSenderId,omitempty"`
	// Email subject line.
	Subject string `json:"subject,omitempty"`
	// HTML email content.
	Message string `json:"message,omitempty"`
	// Optional custom sender name.
	FromName string `json:"fromName,omitempty"`
	// Optional custom reply-to email address.
	ReplyToEmail string `json:"replyToEmail,omitempty"`
	Recipients *Apiv2emailcampaignsRecipients `json:"recipients,omitempty"`
}
