/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type FileMetadata struct {
	// File metadata type.
	Type_ string `json:"type"`
	Height int32 `json:"height"`
	Width int32 `json:"width"`
	Preview *FileMetadataPreview `json:"preview"`
}
