/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Tag struct {
	// Tag ID.
	Id int32 `json:"id"`
	// Tag title.
	Title string `json:"title"`
}
