/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type Conversation struct {
	Id int32 `json:"id"`
	// Message type: inbound or outbound. 
	Direction string `json:"direction"`
	// Sender phone number.
	Sender string `json:"sender"`
	// Time when  the message arrived at Textmagic.
	MessageTime string `json:"messageTime"`
	// Message text.
	Text string `json:"text"`
	// Receiver's phone number.
	Receiver string `json:"receiver"`
	// Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.
	Status string `json:"status"`
	// Contact first name.
	FirstName string `json:"firstName"`
	// Contact last name.
	LastName string `json:"lastName"`
	// Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
	SessionId int32 `json:"sessionId"`
	// Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
	InitiatorId int32 `json:"initiatorId,omitempty"`
	// Message file id.
	MessageFileId int32 `json:"messageFileId,omitempty"`
	// Message type.
	Type_ string `json:"type,omitempty"`
	// Chat type.
	ChatType string `json:"chatType,omitempty"`
	// Chat id.
	ChatId int32 `json:"chatId,omitempty"`
	IsEdited bool `json:"isEdited,omitempty"`
	// Error code.
	ErrorCode string `json:"errorCode,omitempty"`
	Files []*os.File `json:"files,omitempty"`
	Payload *MessagePayload `json:"payload,omitempty"`
	Avatar string `json:"avatar,omitempty"`
}
