/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type MessagesIcs struct {
	// Schedule ID.
	Id int32 `json:"id"`
	// Next send date in [ISO 8601](https://en.wikipedia.org/?title=ISO_8601) format. 
	NextSend time.Time `json:"nextSend"`
	// [iCal RRULE](http://www.kanzaki.com/docs/ical/rrule.html) string. 
	Rrule string `json:"rrule"`
	Session *MessageSession `json:"session"`
	// Date and time when last message has been sent.
	LastSent time.Time `json:"lastSent"`
	// Aggregated contact information. If the message scheduled to be sent to a single contact, a full name will be returned here. Otherwise, a total amount contacts will be returned.
	ContactName string `json:"contactName"`
	Parameters *MessagesIcsParameters `json:"parameters"`
	Type_ string `json:"type"`
	// A human-readable summary of the sending schedule.
	Summary string `json:"summary"`
	TextParameters *MessagesIcsTextParameters `json:"textParameters"`
	// First occurence date.
	FirstOccurrence time.Time `json:"firstOccurrence"`
	// Last occurence date (could be `null` if the schedule is endless).
	LastOccurrence time.Time `json:"lastOccurrence"`
	// Amount of actual recipients.
	RecipientsCount int32 `json:"recipientsCount"`
	// User-friendly timezone name (with spaces replaced by underscores).
	Timezone string `json:"timezone"`
	// Indicates that schedling has been completed.
	Completed bool `json:"completed"`
	// A relative link to the contact avatar.
	Avatar string `json:"avatar"`
	// Scheduling creation time.
	CreatedAt time.Time `json:"createdAt"`
}
