/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MessagePayload struct {
	// Payload type.
	Type_ string `json:"type"`
	// Media preview link.
	MediaPreview string `json:"mediaPreview"`
}
