/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UserPersonalInfo struct {
	// User ID.
	Id int32 `json:"id"`
	// User's first name.
	FirstName string `json:"firstName,omitempty"`
	// User's last name.
	LastName string `json:"lastName,omitempty"`
	// URL to user's avatar image.
	AvatarUrl string `json:"avatarUrl,omitempty"`
	// User's email address.
	Email string `json:"email,omitempty"`
}
