/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type EmailSenderItem struct {
	// Unique email sender identifier.
	Id int32 `json:"id"`
	// ID of the associated domain.
	DomainId int32 `json:"domainId"`
	// Email address of the sender.
	Email string `json:"email"`
	// When the email sender was created.
	CreatedAt string `json:"createdAt"`
	// Current verification status of the associated domain.
	DomainStatus string `json:"domainStatus"`
	// Display name for the sender.
	FromName string `json:"fromName,omitempty"`
	// Reply-to email address.
	ReplyTo string `json:"replyTo,omitempty"`
}
