/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type MessageOutSession struct {
	Id int32 `json:"id,omitempty"`
	StartTime string `json:"startTime,omitempty"`
	Text string `json:"text,omitempty"`
	Price float32 `json:"price,omitempty"`
	NumbersCount int32 `json:"numbersCount,omitempty"`
	Destination string `json:"destination,omitempty"`
	Source string `json:"source,omitempty"`
	ReferenceId string `json:"referenceId,omitempty"`
	InitiatorId int32 `json:"initiatorId,omitempty"`
}
