/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type UpdateContactInputObject struct {
	// Contact first name
	FirstName string `json:"firstName,omitempty"`
	// Contact last name
	LastName string `json:"lastName,omitempty"`
	// Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
	Phone string `json:"phone"`
	// Contact email address.
	Email string `json:"email,omitempty"`
	// Contact company name
	CompanyName string `json:"companyName,omitempty"`
	// Comma-separated [list](http://docs.textmagictesting.com/#section/Lists) ID. Each contact must be assigned to at least one list.
	Lists string `json:"lists"`
	// Is contact marked as favorite.
	Favorited bool `json:"favorited,omitempty"`
	// Is contact blocked for outgoing and incoming messaging.
	Blocked bool `json:"blocked,omitempty"`
	// Force type of phone. Possible values: 0 - landline, 1 - mobile. Default is -1 (auto detection).
	Type_ int32 `json:"type,omitempty"`
	CustomFieldValues []CustomFieldListItem `json:"customFieldValues,omitempty"`
	// Treat phone number passed in request body as **local**.
	Local int32 `json:"local,omitempty"`
	// 2-letter ISO country code for local phone numbers, used when **local** is set to true.
	Country string `json:"country,omitempty"`
}
