/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

// Campaign recipients configuration.
type Apiv2emailcampaignsRecipients struct {
	// Array of contact IDs to send to.
	ContactIds []int32 `json:"contactIds"`
	// Array of email addresses to send to.
	Emails []string `json:"emails"`
	// Array of group IDs to send to.
	GroupIds []int32 `json:"groupIds"`
}
