/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

// Scheduling configuration for the campaign.
type Apiv2emailcampaignsscheduleScheduleParams struct {
	// When to start sending the campaign (ISO 8601 format).
	StartDateTime time.Time `json:"startDateTime"`
	// Timezone for the schedule (e.g., \"America/New_York\").
	Timezone string `json:"timezone"`
	// RFC 5545 recurrence rule for recurring campaigns.
	Rrule string `json:"rrule,omitempty"`
}
