/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type EmailCampaignStatisticTotals struct {
	// Total number of recipients.
	Recipients int32 `json:"recipients"`
	// Number of emails delivered.
	Delivered int32 `json:"delivered"`
	// Number of emails rejected.
	Rejected int32 `json:"rejected"`
	// Number of emails failed to send.
	Failed int32 `json:"failed"`
	// Number of emails opened.
	Opened int32 `json:"opened"`
	// Number of emails with clicks.
	Clicked int32 `json:"clicked"`
	// Number of spam reports.
	SpamReports int32 `json:"spamReports"`
	// Number of unsubscribes.
	Unsubscribed int32 `json:"unsubscribed"`
}
