/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type CreateEmailCampaignResponse struct {
	// Unique campaign ID.
	Id int32 `json:"id"`
	// Current campaign status.
	Status string `json:"status"`
	// Email sender ID used for this campaign.
	EmailSenderId int32 `json:"emailSenderId,omitempty"`
	// Campaign start timestamp.
	StartAt string `json:"startAt"`
	CreatedBy *UserPersonalInfo `json:"createdBy"`
	// Sender name displayed in recipient's inbox.
	FromName string `json:"fromName,omitempty"`
	// Sender email address.
	FromEmail string `json:"fromEmail"`
	// Reply-to email address.
	ReplyToEmail string `json:"replyToEmail"`
	// Email subject line.
	Subject string `json:"subject"`
	// HTML email content.
	Html string `json:"html"`
	// Total campaign cost.
	Cost float32 `json:"cost"`
	Totals *EmailCampaignStatisticTotals `json:"totals"`
	OutboundEmail *OutboundEmailResponse `json:"outboundEmail,omitempty"`
	// Reason for campaign failure if applicable.
	FailedReason string `json:"failedReason,omitempty"`
}
