/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type OutboundEmailResponse struct {
	// Outbound email ID.
	Id int32 `json:"id"`
	// Email send timestamp.
	SendTime string `json:"sendTime"`
	// Sender name.
	FromName string `json:"fromName,omitempty"`
	// Sender email address.
	FromEmail string `json:"fromEmail"`
	// Reply-to email address.
	ReplyToEmail string `json:"replyToEmail"`
	// Recipient's full name.
	RecipientFullName string `json:"recipientFullName,omitempty"`
	// Recipient's email address.
	RecipientEmail string `json:"recipientEmail,omitempty"`
	// Email subject line.
	EmailSubject string `json:"emailSubject"`
	// HTML email content.
	EmailContent string `json:"emailContent"`
	// Source of the outbound email.
	Source string `json:"source"`
	// Current email status.
	Status string `json:"status"`
	// Cost of sending this email.
	Cost float32 `json:"cost"`
	// Detailed status reason.
	StatusReason string `json:"statusReason,omitempty"`
	// Associated contact ID.
	ContactId int32 `json:"contactId,omitempty"`
	// ID of user who initiated the email.
	InitiatorId int32 `json:"initiatorId"`
}
