/*
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

type ScheduledEmailCampaignDetails struct {
	// Unique scheduled campaign ID.
	Id int32 `json:"id"`
	// Current scheduled campaign status.
	Status string `json:"status"`
	// Email sender ID used for this campaign.
	EmailSenderId int32 `json:"emailSenderId,omitempty"`
	// Scheduled start timestamp (UTC).
	StartAt string `json:"startAt"`
	// End timestamp for recurring campaigns (UTC).
	EndAt string `json:"endAt,omitempty"`
	// Next scheduled send timestamp (UTC).
	NextSendAt string `json:"nextSendAt,omitempty"`
	CreatedBy *UserPersonalInfo `json:"createdBy"`
	// Campaign creation timestamp.
	CreatedAt string `json:"createdAt"`
	// Last update timestamp.
	UpdatedAt string `json:"updatedAt"`
	// Campaign recurrence type.
	Type_ string `json:"type"`
	// Sender name displayed in recipient's inbox.
	FromName string `json:"fromName,omitempty"`
	// Sender email address.
	FromEmail string `json:"fromEmail"`
	// Reply-to email address.
	ReplyToEmail string `json:"replyToEmail"`
	// Email subject line.
	Subject string `json:"subject"`
	// HTML email content.
	Html string `json:"html"`
	// Number of recipients for this campaign.
	RecipientsCount int32 `json:"recipientsCount"`
	// Timezone for sending the campaign.
	SendingTimezone string `json:"sendingTimezone"`
	// RFC 5545 recurrence rule for recurring campaigns.
	Rrule string `json:"rrule,omitempty"`
	// Human-readable schedule description.
	OccurrenceSummary string `json:"occurrenceSummary,omitempty"`
}
