/*
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package TextMagic

import (
	"time"
)

type ContactNote struct {
	// Contact note ID.
	Id int32 `json:"id"`
	// Contact note creation time.
	CreatedAt time.Time `json:"createdAt"`
	// Contact note text.
	Note string `json:"note"`
	User *User `json:"user"`
}
